-- Esquema de pruebas para Gestión de almacenes e instalaciones.
-- RLS queda habilitado sin políticas de acceso público: la aplicación usa
-- conexión PostgreSQL privada desde su backend, nunca desde el navegador.
create table if not exists public.warehouses (
    id bigint generated by default as identity primary key,
    name text not null unique,
    active integer not null default 1 check (active in (0, 1)),
    created_at text not null
);

create table if not exists public.employees (
    id bigint generated by default as identity primary key,
    code text not null unique,
    first_name text not null,
    last_name text not null,
    role text not null check (role in ('Técnico', 'Almacenero', 'Supervisor', 'Otro')),
    warehouse_id bigint references public.warehouses(id),
    active integer not null default 1 check (active in (0, 1)),
    created_at text not null
);

create table if not exists public.locations (
    id bigint generated by default as identity primary key,
    name text not null,
    kind text not null check (kind in ('central', 'technician')),
    warehouse_id bigint references public.warehouses(id),
    employee_id bigint unique references public.employees(id),
    created_at text not null,
    check ((kind = 'central' and employee_id is null) or (kind = 'technician' and employee_id is not null))
);

create table if not exists public.items (
    id bigint generated by default as identity primary key,
    code text not null unique,
    name text not null,
    item_type text not null check (item_type in ('Material', 'Equipo')),
    unit text not null,
    serial_control integer not null default 0 check (serial_control in (0, 1)),
    active integer not null default 1 check (active in (0, 1)),
    created_at text not null
);

create table if not exists public.movements (
    id bigint generated by default as identity primary key,
    kind text not null check (kind in ('Ingreso', 'Transferencia')),
    document text not null,
    notes text not null default '',
    responsible text not null,
    created_at text not null
);

create table if not exists public.movement_lines (
    id bigint generated by default as identity primary key,
    movement_id bigint not null references public.movements(id),
    item_id bigint not null references public.items(id),
    source_location_id bigint references public.locations(id),
    destination_location_id bigint not null references public.locations(id),
    quantity double precision not null check (quantity > 0)
);

create table if not exists public.serial_units (
    id bigint generated by default as identity primary key,
    item_id bigint not null references public.items(id),
    serial_number text not null unique,
    current_location_id bigint not null references public.locations(id),
    created_at text not null
);

create table if not exists public.movement_serials (
    id bigint generated by default as identity primary key,
    movement_line_id bigint not null references public.movement_lines(id),
    serial_unit_id bigint not null references public.serial_units(id),
    source_location_id bigint references public.locations(id),
    destination_location_id bigint not null references public.locations(id),
    unique (movement_line_id, serial_unit_id)
);

create table if not exists public.access_roles (
    id bigint generated by default as identity primary key,
    name text not null unique,
    is_system integer not null default 1 check (is_system in (0, 1))
);

create table if not exists public.user_accounts (
    id bigint generated by default as identity primary key,
    employee_id bigint unique references public.employees(id),
    role_id bigint not null references public.access_roles(id),
    username text not null unique,
    password_hash text not null,
    active integer not null default 1 check (active in (0, 1)),
    created_at text not null
);

create table if not exists public.user_warehouse_access (
    user_id bigint not null references public.user_accounts(id) on delete cascade,
    warehouse_id bigint not null references public.warehouses(id),
    primary key (user_id, warehouse_id)
);

create table if not exists public.user_warehouse_permissions (
    user_id bigint not null,
    warehouse_id bigint not null,
    permission text not null,
    effect text not null check (effect in ('allow', 'deny')),
    primary key (user_id, warehouse_id, permission),
    foreign key (user_id, warehouse_id) references public.user_warehouse_access(user_id, warehouse_id) on delete cascade
);

create table if not exists public.login_attempts (
    username_key text primary key,
    failures integer not null,
    window_started_at text not null
);

create table if not exists public.auth_sessions (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.user_accounts(id) on delete cascade,
    token_hash text not null unique,
    expires_at text not null,
    created_at text not null
);

create index if not exists idx_movement_lines_item on public.movement_lines(item_id);
create index if not exists idx_serial_units_location on public.serial_units(current_location_id);
create index if not exists idx_movements_created on public.movements(created_at desc);
create unique index if not exists uq_stock_location_name on public.locations(warehouse_id, lower(name)) where kind = 'central';
create unique index if not exists uq_warehouse_name_ci on public.warehouses(lower(name));
create unique index if not exists uq_employee_code_ci on public.employees(lower(code));
create unique index if not exists uq_item_code_ci on public.items(lower(code));
create unique index if not exists uq_serial_number_ci on public.serial_units(lower(serial_number));
create unique index if not exists uq_role_name_ci on public.access_roles(lower(name));
create unique index if not exists uq_username_ci on public.user_accounts(lower(username));

insert into public.access_roles(name) values
    ('Administrador'), ('Almacenero'), ('Supervisor'), ('Técnico')
on conflict do nothing;

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'warehouses', 'employees', 'locations', 'items', 'movements',
    'movement_lines', 'serial_units', 'movement_serials', 'access_roles',
    'user_accounts', 'user_warehouse_access', 'user_warehouse_permissions',
    'login_attempts', 'auth_sessions'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
  end loop;
end $$;

