-- Shared, administrator-managed values for the article catalog.
create table if not exists public.article_options (
    id bigint generated by default as identity primary key,
    group_key text not null check (group_key in ('item_type', 'unit', 'technology', 'model')),
    value text not null,
    active integer not null default 1 check (active in (0, 1)),
    created_at text not null default now()::text
);

create unique index if not exists uq_article_options_group_value
    on public.article_options(group_key, lower(value));

alter table public.items add column if not exists technology text not null default '';
alter table public.items add column if not exists model text not null default '';

-- Custom article types are defined by article_options, so remove the old
-- Material/Equipo-only check without touching existing article rows.
do $$
declare constraint_name text;
begin
  for constraint_name in
    select conname from pg_constraint
    where conrelid = 'public.items'::regclass and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%item_type%'
  loop
    execute format('alter table public.items drop constraint %I', constraint_name);
  end loop;
end $$;

create table if not exists public.warehouse_item_settings (
    warehouse_id bigint not null references public.warehouses(id) on delete cascade,
    item_id bigint not null references public.items(id) on delete cascade,
    min_stock double precision not null default 0 check (min_stock >= 0),
    primary key (warehouse_id, item_id)
);

insert into public.article_options(group_key, value) values
    ('item_type', 'Material'), ('item_type', 'Equipo'),
    ('unit', 'Unidad'), ('unit', 'Metro'), ('unit', 'Rollo'), ('unit', 'Caja'), ('unit', 'Par'),
    ('technology', 'HFC'), ('technology', 'FTTH'), ('technology', 'Satelital'),
    ('model', 'FIBRA')
on conflict do nothing;

insert into public.article_options(group_key, value)
select distinct 'technology', technology from public.items where technology <> ''
on conflict do nothing;
insert into public.article_options(group_key, value)
select distinct 'model', model from public.items where model <> ''
on conflict do nothing;

alter table public.article_options enable row level security;
alter table public.warehouse_item_settings enable row level security;
revoke all on table public.article_options from anon, authenticated;
revoke all on table public.warehouse_item_settings from anon, authenticated;

